# permissions for end users to view scaledobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaledobject-viewer-role
rules:
- apiGroups:
  - http.keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - http.keda.sh
  resources:
  - scaledobjects/status
  verbs:
  - get
